[env]
DATA_PATH = { glob = "./data/*", include_files = true, include_dirs = false, ignore_type = "git" }
CARGO_MAKE_USE_WORKSPACE_PROFILE = false

[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.gen-data]
condition = { env_set = ["DATA_PATH"] }
command = "cargo"
args = [
    "run",
    "-p", "wat-datagen",
    "--", "knight.wat", "elems.dat", "@@split(DATA_PATH,;)"
]

[tasks.build-wat]
command = "wat2wasm"
args = [
    "--debug-names",
    "knight.wat", "-o", "knight.wasm"
]

[tasks.build]
dependencies = [
    "gen-data",
    "build-wat",
]

[tasks.clean-wat-datagen-src]
command = "cargo"
args = ["clean"]

[tasks.rm-wasm]
command = "rm"
args = ["-f", "knight.wasm"]

[tasks.clean]
dependencies = [
    "clean-wat-datagen-src",
    "rm-wasm"
]

[tasks.run-wasm]
command = "wasmtime"
args = [
    "run",
    "knight.wasm"
]

[tasks.run]
dependencies = [
    "build",
    "run-wasm"
]
